### PR TITLE
update npm to match bower

### PR DESCRIPTION
**Pull request by priley86**
hi - can you please update your npm to match bower? It is confusing to see different versions in the respective package, even though code is the same.

If you would, please merge this PR and npm publish...

### CODE REVIEW

**Comment by tcollard** [comment]
I am actually not the maintainer of the npm package, therefore probably lack publishing rights. Might want to reach out to @mattdsteele

**Comment by mattdsteele** [comment]
I don't have merge rights to this repo so I can't accept the PR, but I've published to NPM as version `1.0.4`.

@tcollard, I can also add you as a maintainer in NPM, just let me know your userid there.

**Comment by priley86** [comment]
@mattdsteele thanks - it may have been best to wait until the PR was version so NPM distribution would match (as you can't republish the same version to NPM again). If this PR is merged, you would want to update bower/npm to `1.0.5`. I've referenced `1.0.4` in our project for now.

**Comment by tcollard** [comment]
Merged. Publish away!

**Comment by priley86** [comment]
i've created [#12](https://github.com/tcollard/google-code-prettify/pull/12) if you want to republish to npm /re-tag bower - just make sure to publish/tag after PR is merged 😄 .

**Pull request merged**
